import type { StoreGame } from '../types/storeTypes'

export const STORE_GAMES: StoreGame[] = [
  {
    id: 'color-sort',
    name: 'Color Sort 3D',
    tagline: 'Sort the colors!',
    description: 'Pour liquid between bottles until each holds a single color. Endless levels.',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationLabel: '3-5 menit',
    playerLabel: '1 pemain',
    path: '/color-sort',
    tone: '#e0452a',
    accent: '#2ec4b6',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'uno',
    name: 'UNO',
    tagline: 'Empty your hand first!',
    description: 'Classic UNO against three bots. Skip, reverse, draw two, up to wild four.',
    category: 'cards',
    categoryLabel: 'Cards',
    durationLabel: '10 menit',
    playerLabel: '2-4 pemain',
    path: '/uno',
    tone: '#8b5cf6',
    accent: '#f0b429',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
  {
    id: 'chess',
    name: 'Chess',
    tagline: 'Checkmate your rival',
    description: 'Classic chess against the Stockfish engine. Pick a level up to world class.',
    category: 'board',
    categoryLabel: 'Board',
    durationLabel: '15 menit',
    playerLabel: '1-2 pemain',
    path: '/chess',
    tone: '#769656',
    accent: '#eeeed2',
    mode: 'bot',
    modeLabel: 'Stockfish',
    isAvailable: true,
  },
  {
    id: 'animal-matching',
    name: 'Animal Matching',
    tagline: 'Match the animals!',
    description: 'Connect two identical animals with at most two turns. Levels get denser.',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationLabel: '5 menit',
    playerLabel: '1 pemain',
    path: '/animal-matching',
    tone: '#2f6d4f',
    accent: '#f0b429',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'maze-runner',
    name: 'Labirin Kumbang',
    tagline: 'Antar kumbang ke gua!',
    description: 'Susuri labirin dan bawa kumbang sampai ke gua sebelum waktu habis. Level makin luas.',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationLabel: '3 menit',
    playerLabel: '1 pemain',
    path: '/maze-runner',
    tone: '#e0452a',
    accent: '#f6c945',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'congklak',
    name: 'Congklak',
    tagline: 'Kumpulkan biji terbanyak!',
    description: 'Congklak tradisional melawan bot. Sebar biji, tembak lubang lawan, penuhi rumahmu.',
    category: 'board',
    categoryLabel: 'Board',
    durationLabel: '10 menit',
    playerLabel: '1-2 pemain',
    path: '/congklak',
    tone: '#6d4bc4',
    accent: '#f0b429',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
]
