import type { StoreGame } from '../types/storeTypes'

export const STORE_GAMES: StoreGame[] = [
  {
    id: 'color-sort',
    name: 'Color Sort 3D',
    tagline: 'Pisahkan warna!',
    description: 'Tuang cairan antar botol sampai tiap botol berisi satu warna. Level tanpa batas.',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    path: '/color-sort',
    tone: '#e0452a',
    accent: '#2ec4b6',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'uno',
    name: 'UNO',
    tagline: 'Habiskan kartu duluan!',
    description: 'Kartu UNO klasik melawan tiga bot. Skip, reverse, draw dua, sampai wild empat.',
    category: 'kartu',
    categoryLabel: 'Kartu',
    path: '/uno',
    tone: '#8b5cf6',
    accent: '#f0b429',
    mode: 'bot',
    modeLabel: 'Lawan Bot',
    isAvailable: true,
  },
  {
    id: 'catur',
    name: 'Catur',
    tagline: 'Skakmat lawanmu',
    description: 'Catur klasik lawan engine Stockfish. Pilih tingkat sampai kelas dunia.',
    category: 'papan',
    categoryLabel: 'Papan',
    path: '/catur',
    tone: '#b58863',
    accent: '#f0b429',
    mode: 'bot',
    modeLabel: 'Stockfish',
    isAvailable: true,
  },
]
